version: '3'

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - panel_data:/app/var
    environment:
      - APP_URL=http://localhost
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=pterodactyl
      - DB_USERNAME=ptero
      - DB_PASSWORD=somepassword

  mariadb:
    image: mariadb:10.5
    container_name: pterodactyl_db
    restart: always
    environment:
      MYSQL_DATABASE: pterodactyl
      MYSQL_USER: ptero
      MYSQL_PASSWORD: somepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  panel_data:
  db_data:

